FROM docker.io/ubuntu
MAINTAINER test@gmail.com
RUN mkdir /tmp/d1
RUN mkdir /tmp/d2
WORKDIR /tmp/d1
ADD https://bunnyacademy.b-cdn.net/what-is-docker.png /tmp
ADD index.html /tmp
ADD . .
ADD 1.tar.gz /tmp/d2
#add can copy to container
#add can have url as source
#add can copy tar and untar file to container
 
